# debug
debug:
  true
# database
#spring.r2dbc.url=r2dbc:mysql://localhost:3306/testDeploy?useUnicode=true&characterEncoding=UTF-8
#spring.r2dbc.username=root
#spring.r2dbc.password=123456
# log
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
#spring:
#  flyway:
#    enabled: false
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
